from pathlib import Path
from typing import Any, Final

import yaml
from pydantic import BaseModel

from weekend_loop.models import (
    Backend,
    IdentityPolicy,
    Policy,
    RepoMode,
    RepoTarget,
    SchedulePolicy,
    Workspace,
)

EXAMPLE_REPO_KEY: Final[str] = "myrepo"
EXAMPLE_SLUG: Final[str] = "your-org/your-repository"
EXAMPLE_EMAIL: Final[str] = "you@example.com"
EXAMPLE_GATE_COMMAND: Final[str] = "pytest -q"
EXAMPLE_WORKSPACE: Final[Path] = Path("~/.weekend-loop")
REFERENCE_HEADER: Final[str] = (
    "# Every key Weekend Loop reads, with the value it takes when your config.yaml leaves it out.\n"
    "# Generated by `weekend-loop config reference`; nothing reads this file.\n"
)
RESOLVED_HEADER_TEMPLATE: Final[str] = "# the configuration this workspace runs under: {root}\n"
WORKSPACE_FIELD: Final[str] = "workspace"


def example_policy() -> Policy:
    return Policy(
        workspace=Workspace(root=EXAMPLE_WORKSPACE),
        repos={
            EXAMPLE_REPO_KEY: RepoTarget(
                slug=EXAMPLE_SLUG,
                mode=RepoMode.DRY_RUN,
                backend=Backend.GITHUB,
                gate_commands=[EXAMPLE_GATE_COMMAND],
            )
        },
        identity=IdentityPolicy(git_author_email=EXAMPLE_EMAIL),
        schedule=SchedulePolicy(repo_key=EXAMPLE_REPO_KEY),
    )


def as_document(policy: Policy) -> dict[str, Any]:
    document: dict[str, Any] = policy.model_dump(mode="json", exclude={WORKSPACE_FIELD})
    return document


def reference_document() -> str:
    return REFERENCE_HEADER + yaml.safe_dump(as_document(example_policy()), sort_keys=False)


def resolved_document(policy: Policy) -> str:
    header = RESOLVED_HEADER_TEMPLATE.format(root=policy.workspace.root)
    return header + yaml.safe_dump(as_document(policy), sort_keys=False)


def unset_keys(model: BaseModel, prefix: str) -> list[str]:
    keys: list[str] = []
    for name in type(model).model_fields:
        dotted = f"{prefix}{name}"
        value = getattr(model, name)
        if isinstance(value, BaseModel):
            keys.extend(unset_keys(value, f"{dotted}."))
        elif name not in model.model_fields_set:
            keys.append(dotted)
    return keys


def default_keys(policy: Policy) -> list[str]:
    return [key for key in unset_keys(policy, "") if not key.startswith(WORKSPACE_FIELD)]
